export const GET_INGREDIENTS_REQUEST = "GET_INGREDIENTS_REQUEST";
export const GET_INGREDIENTS_SUCCESS = "GET_INGREDIENTS_SUCCESS";
export const GET_INGREDIENTS_FAILED = "GET_INGREDIENTS_FAILED";

export const SET_INGREDIENTS_CONSTRUCTOR = "SET_INGREDIENTS_CONSTRUCTOR";

export const ADD_INGREDIENTS_DETAILS = "ADD_INGREDIENTS_DETAILS";
export const DEL_INGREDIENTS_DETAILS = "DEL_INGREDIENTS_DETAILS";

export const SET_ORDER_NUMBER = "SET_ORDER_NUMBER";
