export const AUTH_CHECKED: "AUTH_CHECKED" = "AUTH_CHECKED";
export const SET_USER: "SET_USER" = "SET_USER";
export const LOGOUT_USER: "LOGOUT_USER" = "LOGOUT_USER";
export const RESET_PASSWORD_FINISHED: "RESET_PASSWORD_FINISHED" =
  "RESET_PASSWORD_FINISHED";
export const RESET_PASSWORD_STARTED: "RESET_PASSWORD_STARTED" =
  "RESET_PASSWORD_STARTED";
