export const ADD_BUN_CONSTRUCTOR: "ADD_BUN_CONSTRUCTOR" = "ADD_BUN_CONSTRUCTOR";
export const ADD_INGREDIENT_CONSTRUCTOR: "ADD_INGREDIENT_CONSTRUCTOR" =
  "ADD_INGREDIENT_CONSTRUCTOR";
export const DEL_INGREDIENT_CONSTRUCTOR: "DEL_INGREDIENT_CONSTRUCTOR" =
  "DEL_INGREDIENT_CONSTRUCTOR";
export const UPDATE_LIST_INGREDIENTS_CONSTRUCTOR: "UPDATE_LIST_INGREDIENTS_CONSTRUCTOR" =
  "UPDATE_LIST_INGREDIENTS_CONSTRUCTOR";
export const CLEAR_LIST_INGREDIENTS_CONSTRUCTOR: "CLEAR_LIST_INGREDIENTS_CONSTRUCTOR" =
  "CLEAR_LIST_INGREDIENTS_CONSTRUCTOR";
